# Generated by Django 5.1.3 on 2024-11-23 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('courier', models.CharField(choices=[('fedex', 'FedEx'), ('ups', 'UPS'), ('usps', 'USPS'), ('dhl', 'DHL'), ('amazon', 'Amazon')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('barcode_data', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
            ],
            options={
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.CharField(max_length=50, unique=True)),
                ('zone', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('packages', models.ManyToManyField(related_name='invoices', to='api.package')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storagelocation'),
        ),
    ]
