services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mailroom
      - POSTGRES_USER=mailroom_user
      - POSTGRES_PASSWORD=your_secure_password
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://mailroom_user:your_secure_password@db:5432/mailroom
      - DEBUG=1
      - SECRET_KEY=your_secret_key_here
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - DJANGO_SETTINGS_MODULE=core.settings

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000/api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

# Define volumes
volumes:
  postgres_data:  # This was missing
  static_volume: